spring:
  config:
    import: optional:file:.env[.properties]
  # Security - OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:hoho}
            client-secret: ${GOOGLE_CLIENT_SECRET:hoho}
            scope: profile,email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:hoho}
            client-secret: ${FACEBOOK_CLIENT_SECRET:hoho}
            scope: email,public_profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  # database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/smartlogi_dms
    username: human
    password: ahmed
    driver-class-name: org.postgresql.Driver

  #  jpa / hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 830474a69ff1fd
    password: 4898348e8874f5 # Use app password for Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

logging:
  level:
    root: INFO
    com.smartlogi.smartlogidms: DEBUG

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #    console: "%d{yyyy-MM-dd HH:mm:ss} %clr([%thread]){faint} %clr(%-5level){%style{INFO=blue,WARN=yellow,ERROR=red}} %clr(%logger{36}){cyan} - %msg%n"
  #    console: "%d{yyyy-MM-dd HH:mm:ss} %clr([%thread]){faint} %highlight(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  file:
    name: logs/myapp.log
app:
  base-url: http://localhost:8080

tawdi:
  jwt:
    secret: "dfghjkLKJHGFDHjlkjhGFHJK09876545678LKJFGHjKJVBNdfghjjhg"
    expiration-ms: 3600000
