spring:
  # database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/smartlogi_dms
    username: human
    password: ahmed
    driver-class-name: org.postgresql.Driver

  #  jpa / hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    root: INFO
    com.smartlogi.smartlogidms: DEBUG

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} %clr([%thread]){faint} %clr(%-5level){%style{INFO=blue,WARN=yellow,ERROR=red}} %clr(%logger{36}){cyan} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} %clr([%thread]){faint} %highlight(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  file:
    name: logs/myapp.log
